### ISSUE TITLE
Change amps on runtime

### ISSUE THREAD

**Issue by mishushakov** [keyth72/SmartGuitarAmp#11]
what's missing is a format for packaging amps
currently, you have to rebuild the binary if you want your own model + overlay

we could just zip our models and skins under a flashy extension (.amp?) and browse them in the plugin
appreciate your time and feedback

**Comment by GuitarML** [comment]
Issue clean up, no current plans to implement different skins for SmartAmp, would not be opposed to someone taking this on themselves though.
