### ISSUE TITLE
feature request: linux version

### ISSUE THREAD

**Issue by magnetophon** [keyth72/SmartGuitarAmp#2]
Thanks for making this, under an open license!
I'd love to use it, but am using linux.
Since it's based on JUCE it should not be too hard to port it.
Any chance on that?

**Comment by keyth72** [comment]
Yes, I’m planning on releasing an Ubuntu Linux version. I can do other flavors of Linux as well if there’s an interest in that.

**Comment by trebmuh** [comment]
I'd like to test this on linux too.
@keyth72 : if you provide a "how to build" paragraph, we might be able to find our way ourselves, saving your time.

**Comment by keyth72** [comment]
That would be great, check out the Initial Setup section of the Readme for build instructions (I might change the title of that section to be more clear). If there are some gaps in the instructions let me know and I’ll walk you through it.

**Comment by magnetophon** [comment]
@keyth72 That's great to hear, thanks!

I'd personally also much prefer some good build instructions over a binary, because that way everybody can use it, and it can be packaged for many distributions.

**Comment by mishushakov** [comment]
if you could add a makefile or a build script, we could make a GitHub Action to build + package/distribute automatically

**Comment by keyth72** [comment]
That does sound like a good idea, I like automation when I can use it.  However using JUCE for the framework takes care of most of the build headaches and allows cross platform builds without needing platform specific scripts.  It does require a manual process though so I see the merit in doing the GitHub action with build scripts. I’d be happy to incorporate changes via pull requests, otherwise I’ll add it to my todo list.

**Comment by keyth72** [comment]
Ubuntu Linux release is available, I'll leave this issue open to allow time for feedback.

**Comment by viccuad** [comment]
Many thanks for considering a Linux version!
Perhaps the Linux version could be based in lv2? One cannot build and distribute VST plugins easily, since VST SDK is under a privative license and it can't be compiled and redistributed. This leaves distributions with no legal way to have a VST SDK to build and ship VST plugins.

**Comment by keyth72** [comment]
The Linux version is already available in the project release page (Ubuntu). This plugin is built with the JUCE framework which makes it easy to build VST format on Linux.

**Comment by magnetophon** [comment]
@viccuad You seem to be a bit misinformed here.  :) 

> Many thanks for considering a Linux version!

The linux version is not considered anymore, it is out; announced in the post above yours.

> since VST SDK is under a privative license and it can't be compiled and redistributed. 
 
This is true for VST2, but not for VST3, which has an open license.
This plugin is a VST3.

However, I *do* agree an LV2 would be great, but that is because there are very few linux plugin hosts that support VST3.

**Comment by mxmilkiib** [comment]
N.b. There are two slightly different JUCE forks that can target LV2; https://github.com/DISTRHO/juce/tree/juce6 of @falktx and https://github.com/lv2-porting-project/JUCE of @kottv. The manual step can also be worked around [like so(https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=bespokesynth-git#n35).

**Comment by keyth72** [comment]
Have not heard of any issues running the Ubuntu linux version, closing issue.

**Comment by magnetophon** [comment]
Sorry for the late reply.

I have not been able to test it yet.
The problem is that on the distro I use (NixOS), it's hard to run programs that are not built from source on that distro.
The solution would be a way to compile without installing Juce.
I can fully understand if that is not worth it to you though.

In any case thanks for making a linux version available!
