### ISSUE TITLE
GUI front end for training models?

### ISSUE THREAD

**Issue by chipmcdonald** [keyth72/SmartGuitarAmp#5]
Is this possible?  I'm not a programmer by trade, the last time I messed with Python it was an hours long debacle.  I think you'd see a big leap in attention if people could experiment with trying to train their own models...

**Comment by keyth72** [comment]
Yes its definitely possible to do, it would be great to have a one click solution to upload some wav files and generate a model. Probably a good next step in development.

**Comment by keyth72** [comment]
Going to close this issue, it really belongs in the PedalNetRT project. There is a docker implementation in the works that would make the GUI idea easier to do, so I’ll leave it for that project.
